### ISSUE TITLE
Using system tzdb instead of submodule

### ISSUE THREAD

**Issue by Tachi107** [lat9nq/tzdb_to_nx#16]
Hi, is it currently possible to use `tzdb_to_nx` to convert time zone data installed system-wide (like with the [`tzdata`](https://packages.debian.org/testing/all/tzdata/filelist) Debian package) to the nx format, avoiding usage of the `tz` submodule? I see that the submodule is only accessed if `TZ_DIR` and `TZIF_LIST_FILE` are not already set to something that exists, but after setting the first to "`/`" and the second to the output of "`find /usr/share/zoneinfo -type f,l -exec 'grep' '-l' '^TZif' '{}' '+' | sort > tzif.txt`" (which outputs all the TZif files present in /usr/share/zoneinfo by checking if they start with the `TZif` characters), I don't know how to proceed.

Thanks!

**Comment by lat9nq** [comment]
It should be possible. Currently I avoid this: instead I pick a specific commit from eggert/tz to match the Switch's time zone binary as closely as possible.

While this provides an output that byte-for-byte matches the Switch's firmware (currently matching 17.0.?), this doesn't mean local builds shouldn't be allowed play around with other source files. I am open to making this a CMake option if that's what you're asking or wanting to do.

**Comment by Tachi107** [comment]
> It should be possible. Currently I avoid this: instead I pick a specific commit from eggert/tz to match the Switch's time zone binary as closely as possible.
> 
> While this provides an output that byte-for-byte matches the Switch's firmware (currently matching 17.0.?)

Understood, thanks!

> this doesn't mean local builds shouldn't be allowed play around with other source files. I am open to making this a CMake option if that's what you're asking or wanting to do.

Yep, that's exactly what I'd like to have. I tried implementing it myself, but still haven't been able to do so. I'll give it another shot, but if you already know how to do it please let me know :)

**Comment by Tachi107** [comment]
For now I'm using this (terrifying) command line which seems to work:

    c++ src/tzdb2nx/*.cpp -o tzdb2nx && find /usr/share/zoneinfo -type f,l -exec 'grep' '-l' '^TZif' '{}' '+' | sort | sed 's|/usr/share/zoneinfo/||' | xargs -I tzif_file sh -c 'dirname tzif_file | xargs mkdir -p && ./tzdb2nx /usr/share/zoneinfo/tzif_file tzif_file'

But an upstream solution would be better :)
